config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :reviews
  end
  resources :users
  resources :revieweds do
    resources :ureviews
  end
  
  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
    member do
      post :restore
    end
    collection do
      delete :empty_trash
    end
    member do
     post :mark_as_read
   end
  end

  get '/hello/there', to: 'hello#there'
  root to: 'pages#home'
  get "/pages/:page" => "pages#show"
  get "pages/profile/myprojects" => "projects#myprojects"
  delete "/relationships", to: "relationships#destroy"
  resources :relationships, only: [:create]
  delete "/friendships", to: "friendships#destroy"
  resources :friendships, only: [:create]
  get "/my_friends", to: "users#my_friends"
  get "/users" => "users#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :relationships
  has_many :reviews
  def	followers?(user_id)
  		self.relationships.find_by_user_id(user_id)
	end

  validates :mentor, presence:true
  validates :price, numericality:true
  validate do |project|
    GoodnessValidator.new(project).validate
  end
  # Project.exists?(["mentor LIKE ?", "%#{params[:search]}"])

  has_attached_file :file
  validates_attachment :file, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document application/text) }

end

class GoodnessValidator
  def initialize(project)
    @project = project
  end

  def validate
    # if User.where(:name => @project_mentor).blank?
    if User.exists?(email: @project.mentor)
      nil
    else
      @project.errors[:base] << "Такого нету"
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/ureview.rb
class Ureview < ApplicationRecord
  belongs_to :user
  belongs_to :reviewed, class_name: 'User', foreign_key: 'reviewed_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  validates :name, presence:true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  acts_as_messageable

  has_many :projects
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100#", large: "600x600>"}, default_url: "http://www.pi-cube.com/wp-content/uploads/2015/04/team-placeholder.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_many :relationships
  has_many :reviews
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :ureviews

  def mailboxer_email(object)
    email
  end

  def	following?(project_id)
		self.relationships.find_by_project_id(project_id)
	end

  def followinguser?(friend_id)
    self.friendships.find_by_friend_id(friend_id)
  end
  def	followuser(friend_id)
		self.friendships.create(friend_id: friend_id)
	end
  def	unfollowuser(friend_id)
		self.friendships.find_by_friend_id(friend_id).destroy if followinguser?(friend_id)
	end
	def	follow(project_id)
		self.relationships.create(project_id: project_id)
	end
  def	unfollow(project_id)
		self.relationships.find_by_project_id(project_id).destroy if following?(project_id)
	end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end


  def show
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to projects_path
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_project
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :check_sign_in, only: [:create, :edit, :new, :destroy, :update]
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.project_id = @project.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end
  
  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to project_path(@project)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to project_path(@project)
  end

  private
    def review_params
      params.require(:review).permit(:rating, :comment)
    end

    def find_project
      @project = Project.find(params[:project_id])
    end

    def find_review
      @review = Review.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_sign_in, only: [:show, :index, :my_friends]
  def index
    @users = User.where(["name LIKE ?","%#{params[:search]}"])
  end
  def show
    @user	=	User.find(params[:id])
  end
  def my_friends
    @friends = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, size = 30, title = user.name)
    image_tag gravatar_image_url(user.email, size: size), title: title, class: 'img-rounded'
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options(chosen_recipient = nil)
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}' data-img-src='#{gravatar_image_url(user.email, size: 50)}' #{'selected' if user == chosen_recipient}>#{user.name}</option>"
    end
    s.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/ureviews_helper.rb
module UreviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/_conversations.html.erb
<li class="list-group-item clearfix">
  <%= link_to conversations.subject, conversations_path(conversations) %>

  <div class="btn-group-vertical pull-right">
    <% if conversations.is_trashed?(current_user) %>
      <%= link_to 'Restore', restore_conversation_path(conversations), class: 'btn btn-xs btn-info', method: :post %>
    <% else %>
      <%= link_to 'Move to trash', conversation_path(conversations), class: 'btn btn-xs btn-danger', method: :delete,
                  data: {confirm: 'Are you sure?'} %>

      <% if conversations.is_unread?(current_user) %>
        <%= link_to 'Mark as read', mark_as_read_conversation_path(conversations),
                  class: 'btn btn-xs btn-info', method: :post %>
        <% end %>
    <% end %>

  </div>

  <p><%= render 'conversations/participants', conversation: conversations %></p>


  <p><%= conversations.last_message.body %>
    <small>(<span class="text-muted"><%= conversations.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small>
  </p>
</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
    <%= gravatar_for participant %>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<div class="row1">
  <div class="col-sm-3">
    <ul class="nav nav-pills nav-stacked">
      <%= link_to 'Send message', new_message_path %>
      <%= mailbox_section 'inbox', @box %>
      <%= mailbox_section 'sent', @box %>
      <%= mailbox_section 'trash', @box %>
    </ul>
  </div>

  <div class="col-sm-9">
    <% if @box == 'trash' %>
     <p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,
                    data: {confirm: 'Are you sure?'} %></p>
    <% end %>
    <ul class="list-group">
      <%= render partial: 'conversations/conversations', collection: @conversations %>
    </ul>

    <%= will_paginate %>
  </div>
</div>

app/views/conversations/show.html.erb
<p>Chatting with
  <%= render 'conversations/participants', conversation: @conversation %>
</p>

<div class="panel panel-default">
  <div class="panel-heading"><%= @conversation.subject %></div>

  <div class="panel-body">
    <div class="messages">
      <% @conversation.receipts_for(current_user).each do |receipt| %>
        <div class="media">
          <% message = receipt.message %>
          <div class="media-left">
            <%= gravatar_for message.sender, 45, message.sender.name %>
          </div>

          <div class="media-body">
            <h6 class="media-heading"><%= message.sender.name %>
              says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></h6>
            <%= message.body %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= form_tag reply_conversation_path(@conversation), method: :post do %>
  <div class="form-group">
    <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
  </div>
  <%= submit_tag "Send Message", class: 'btn btn-primary' %>
<% end %>