config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :reviews
  end
  resources :users
  resources :revieweds do
    resources :ureviews
  end
  
  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
    member do
      post :restore
    end
    collection do
      delete :empty_trash
    end
    member do
     post :mark_as_read
   end
  end

  get '/hello/there', to: 'hello#there'
  root to: 'pages#home'
  get "/pages/:page" => "pages#show"
  get "pages/profile/myprojects" => "projects#myprojects"
  delete "/relationships", to: "relationships#destroy"
  resources :relationships, only: [:create]
  delete "/friendships", to: "friendships#destroy"
  resources :friendships, only: [:create]
  get "/my_friends", to: "users#my_friends"
  get "/users" => "users#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :relationships
  has_many :reviews
  def	followers?(user_id)
  		self.relationships.find_by_user_id(user_id)
	end

  validates :mentor, presence:true
  validates :price, numericality:true
  validate do |project|
    GoodnessValidator.new(project).validate
  end
  # Project.exists?(["mentor LIKE ?", "%#{params[:search]}"])

  has_attached_file :file
  validates_attachment :file, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document application/text) }

end

class GoodnessValidator
  def initialize(project)
    @project = project
  end

  def validate
    # if User.where(:name => @project_mentor).blank?
    if User.exists?(email: @project.mentor)
      nil
    else
      @project.errors[:base] << "Такого нету"
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/ureview.rb
class Ureview < ApplicationRecord
  belongs_to :user
  belongs_to :reviewed, class_name: 'User', foreign_key: 'reviewed_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  validates :name, presence:true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  acts_as_messageable

  has_many :projects
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100#", large: "600x600>"}, default_url: "http://www.pi-cube.com/wp-content/uploads/2015/04/team-placeholder.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_many :relationships
  has_many :reviews
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :ureviews

  def mailboxer_email(object)
    email
  end

  def	following?(project_id)
		self.relationships.find_by_project_id(project_id)
	end

  def followinguser?(friend_id)
    self.friendships.find_by_friend_id(friend_id)
  end
  def	followuser(friend_id)
		self.friendships.create(friend_id: friend_id)
	end
  def	unfollowuser(friend_id)
		self.friendships.find_by_friend_id(friend_id).destroy if followinguser?(friend_id)
	end
	def	follow(project_id)
		self.relationships.create(project_id: project_id)
	end
  def	unfollow(project_id)
		self.relationships.find_by_project_id(project_id).destroy if following?(project_id)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to projects_path
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_project
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :check_sign_in, only: [:create, :edit, :new, :destroy, :update]
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.project_id = @project.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end
  
  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to project_path(@project)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to project_path(@project)
  end

  private
    def review_params
      params.require(:review).permit(:rating, :comment)
    end

    def find_project
      @project = Project.find(params[:project_id])
    end

    def find_review
      @review = Review.find(params[:id])
    end
end

app/controllers/ureviews_controller.rb
class UreviewsController < ApplicationController
  before_action :find_reviewed
  before_action :find_ureview, only: [:edit, :update, :destroy]
  before_action :check_sign_in, only: [:create, :edit, :new, :destroy, :update]
  def new
    @ureview = Ureview.new
  end

  def create
    @ureview = Ureview.new(ureview_params)
    @ureview.reviewed_id = @reviewed.id
    @ureview.user_id = current_user.id

    if @ureview.save
      redirect_to user_path(@reviewed)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @ureview.update(ureview_params)
      redirect_to user_path(@reviewed)
    else
      render 'edit'
    end
  end

  def destroy
    @ureview.destroy
    redirect_to user_path(@reviewed)
  end

  private
    def ureview_params
      params.require(:ureview).permit(:ucomment, :uratingone, :uratingtwo, :uratingthree, :uratingfour, :uratingfive)
    end

    def find_reviewed
      @reviewed = User.find(params[:reviewed_id])
    end

    def find_ureview
      @ureview = Ureview.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_sign_in, only: [:show, :index, :my_friends]
  def index
    @users = User.where(["name LIKE ?","%#{params[:search]}"])
  end
  def show
    @user	=	User.find(params[:id])
  end
  def my_friends
    @friends = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, size = 30, title = user.name)
    image_tag gravatar_image_url(user.email, size: size), title: title, class: 'img-rounded'
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options(chosen_recipient = nil)
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}' data-img-src='#{gravatar_image_url(user.email, size: 50)}' #{'selected' if user == chosen_recipient}>#{user.name}</option>"
    end
    s.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/ureviews_helper.rb
module UreviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ureviews/_form.html.erb
<%= form_for([@reviewed, @reviewed.ureviews.build], url: reviewed_ureviews_url) do |f| %>
  <div id="ratingone-form">
    <label> Энтузиазм </label>
  </div>
  <div id="ratingtwo-form">
    <label> Качество работы </label>
  </div>
  <div id="ratingthree-form">
    <label> Взаимоуважение  </label>
  </div>
  <div id="ratingfour-form">
    <label> Опыт </label>
  </div>
  <div id="ratingfive-form">
    <label> Адаптивность </label>
  </div>
  <%= f.label :Коментарии %><br>
  <%= f.text_field :ucomment %>
  <%= f.submit "create" %>
<% end %>
<script>
  $('#ratingone-form').raty({
    path: '/assets/',
    scoreName: 'ureview[uratingone]'
  });
</script>
<script>
  $('#ratingtwo-form').raty({
    path: '/assets/',
    scoreName: 'ureview[uratingtwo]'
  });
</script>
<script>
  $('#ratingthree-form').raty({
    path: '/assets/',
    scoreName: 'ureview[uratingthree]'
  });
</script>
<script>
  $('#ratingfour-form').raty({
    path: '/assets/',
    scoreName: 'ureview[uratingfour]'
  });
</script>
<script>
  $('#ratingfive-form').raty({
    path: '/assets/',
    scoreName: 'ureview[uratingfive]'
  });
</script>

app/views/ureviews/_ureview.html.erb
<div class="review">
  <p>от: <%= link_to ureview.user_id, ureview.user%> | <%= link_to ureview.user.email, ureview.user%></p>
  <p>для: <%= ureview.reviewed_id%> | <%= ureview.reviewed.email%></p>
  <div class="review">
    <div class="review-rating" data-source="<%= ureview.uratingone %>">  Энтузиазм </div>
    <div class="review-rating" data-source="<%= ureview.uratingtwo %>"> Качество работы </div>
    <div class="review-rating" data-source="<%= ureview.uratingthree %>"> Взаимоуважение </div>
    <div class="review-rating" data-source="<%= ureview.uratingfour %>"> Опыт </div>
    <div class="review-rating" data-source="<%= ureview.uratingfive %>"> Адаптивность </div>

    <% av = ureview.uratingone + ureview.uratingtwo + ureview.uratingthree + ureview.uratingfour + ureview.uratingfive%>

    <div class="review-rating" data-source="<%= av/5 %>"> Average </div>



  </div>
  <p class="review-comment">Коментарии: <%= ureview.ucomment %></p>
  <div class="links btn-group">
    <%= link_to "Edit", edit_reviewed_ureview_path(ureview.reviewed, ureview)%>
    <%= link_to "Delete", reviewed_ureview_path(ureview.reviewed, ureview), method: :delete, data: { confirm: "Are you sure?"}%>
  </div>
</div>

app/views/ureviews/edit.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="edit-review-form">
<h1> Edit Review </h1>
  <%= form_for([@reviewed, @ureview], url:  edit_reviewed_ureview_url) do |f| %>
    <div id="ratingone-form">
      <label> Rating </label>
    </div>
    <div id="ratingtwo-form">
      <label> Rating </label>
    </div>
    <div id="ratingthree-form">
      <label> Rating </label>
    </div>
    <div id="ratingfour-form">
      <label> Rating </label>
    </div>
    <div id="ratingfive-form">
      <label> Rating </label>
    </div>
    <%= f.label :ucomment %><br>
    <%= f.text_field :ucomment %>
    <%= f.submit "create"%>
  <% end %>
</div>
</div>
<input type="button" onclick="history.back();" value="Назад"/>
<script>
  $('#ratingone-form').raty({
    path: '/assets/',
    scoreName: 'ureview[uratingone]'
  });
</script>
<script>
  $('#ratingtwo-form').raty({
    path: '/assets/',
    scoreName: 'ureview[uratingtwo]'
  });
</script>
<script>
  $('#ratingthree-form').raty({
    path: '/assets/',
    scoreName: 'ureview[uratingthree]'
  });
</script>
<script>
  $('#ratingfour-form').raty({
    path: '/assets/',
    scoreName: 'ureview[uratingfour]'
  });
</script>
<script>
  $('#ratingfive-form').raty({
    path: '/assets/',
    scoreName: 'ureview[uratingfive]'
  });
</script>

app/views/ureviews/new.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="new-review-form">
<h1> Фидбэк </h1>
<%= render 'form' %>
</div>
</div>
<input type="button" onclick="history.back();" value="Назад"/>