config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :reviews
  end
  resources :users
  resources :revieweds do
    resources :ureviews
  end
  
  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
    member do
      post :restore
    end
    collection do
      delete :empty_trash
    end
    member do
     post :mark_as_read
   end
  end

  get '/hello/there', to: 'hello#there'
  root to: 'pages#home'
  get "/pages/:page" => "pages#show"
  get "pages/profile/myprojects" => "projects#myprojects"
  delete "/relationships", to: "relationships#destroy"
  resources :relationships, only: [:create]
  delete "/friendships", to: "friendships#destroy"
  resources :friendships, only: [:create]
  get "/my_friends", to: "users#my_friends"
  get "/users" => "users#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :relationships
  has_many :reviews
  def	followers?(user_id)
  		self.relationships.find_by_user_id(user_id)
	end

  validates :mentor, presence:true
  validates :price, numericality:true
  validate do |project|
    GoodnessValidator.new(project).validate
  end
  # Project.exists?(["mentor LIKE ?", "%#{params[:search]}"])

  has_attached_file :file
  validates_attachment :file, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document application/text) }

end

class GoodnessValidator
  def initialize(project)
    @project = project
  end

  def validate
    # if User.where(:name => @project_mentor).blank?
    if User.exists?(email: @project.mentor)
      nil
    else
      @project.errors[:base] << "Такого нету"
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :check_sign_in, only: [:create, :edit, :new, :destroy, :update, :myprojects, :show]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.where(["title LIKE ?","%#{params[:search]}"])
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @data = params[:text1]
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project =  current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def myprojects
    @myprojects = Project.all
  end
  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :price, :mentor, :file, :sts, :deadline)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="project_form ">
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %>
      prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="col-2">
      <label class = "main_labels">
        <%= f.label 'Название' %>
        <%= f.text_field :title,placeholder:"Название вашей задачи"%>
      </label>
    </div>
    <div class="col-2">
      <label class = "main_labels">
        <%= f.label 'Описание' %>
        <%= f.text_field :description, rows: 6, placeholder:"Описание задачи, гипотеза решения" %>
      </label>
    </div>

    <div class="col-3">
      <label class = "main_labels">
        <%= f.label :Вознаграждение%>
        <%= f.text_field :price,placeholder:"Введите сумму" %>
      </label>
    </div>

    <div class="col-3">
      <label class = "main_labels">
        <%= f.label 'Сроки выполнения' %>
        <%= f.date_field :deadline%>
      </label>
    </div>
    <div class="col-3">
      <label class = "main_labels">
        <%= f.label :Ментор %>
        <%= f.email_field :mentor,placeholder:"Введите его почту"%>
      </label>
    </div>

    <div class="col-lg-12 mentor">
      <label class = "radio_labels">

          <div class="clear_me row col-lg-4 col-lg-offset-4 col-xs-8 col-xs-offset-2">
            <%= f.label :sts , 'В процессе', :value => "1"%>
            <%= f.radio_button :sts, '1'%>
          </div>
          <div class="clear_me row col-lg-4 col-lg-offset-4 col-xs-8 col-xs-offset-2">
            <%= f.label :sts , 'На рассмотрении', :value => "0"%>
            <%= f.radio_button :sts, '0' %>
          </div>
          <div class="clear_me row col-lg-4 col-lg-offset-4 col-xs-8 col-xs-offset-2">
            <%= f.label :sts , 'Завершен', :value => "-1"%>
            <%= f.radio_button :sts, '-1' %>
          </div>






      </label>
    </div>
    <div class="actions">
      <%= f.submit "Создать" , class:"create_button"%>
    </div>


<% end %>
</div>

app/views/projects/edit.html.erb
<% if user_signed_in?%>
  <% if current_user.email == @project.user.email || current_user.email == @project.mentor%>
    <h1>Editing Project</h1>

    <%= render 'form', project: @project %>

    <%= link_to 'Show', @project %> |
    <%= link_to 'Back', projects_path %>
  <% else %>
    <h1>К сожалению, у вас нет полномочий на изменение этого проекта</h1>
  <% end %>
<% end %>

app/views/projects/index.html.erb
<body>
<%= form_tag projects_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Поиск" %>
<% end %>
<br/>

<% @projects.each do |project| %>
<div class="mikaskazala col-lg-9 col-md-9" >
  <div class="project fadeInRight wow" data-wow-duration="2s">
    <table class="projects_preview">
      <tr style="border-radius:10px;">
        <td class = "projects_preview_img_td">
          <%= image_tag project.user.avatar(:thumb),class:"projects_preview_img" %>
        </td>
        <td class="description">
          <h4><%= project.title %></h4>
          <h6 class = "from"><%= project.user.email %> <br>
          <% count = 0 %>
          <% if project.sts != -1 %>
            <% User.all.each do |user| %>
              <% if project.followers?(user.id) %>
                <% if user.name == ""%>
                  <% project.sts = 0%>
                  <% project.save%>
                <% else %>
                  <% project.sts = 1%>
                  <% project.save%>
                  <% count+=1 %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
          Проект делают: <%= count %>
          <% if count > 0%>
            <h4>в процессе</h4>
          <% elsif count == 0 && project.sts != -1%>
            <h4>в рассмотрении</h4>
            <% project.sts = 0%>
            <% project.save%>
          <% elsif project.sts == -1%>
            <h4>закончен</h4>
          <% end %>
          </h6>
        </td>
        <td class="date">
          До: <%= project.deadline %></br>
          <% a=Date.parse(Time.now.strftime("%Y/%m/%d"))%>
          <p class = "days_left">Осталось дней: <%= (project.deadline.mjd-a.mjd) %></p>
          Цена: <%= project.price %> тг
        </td>
        <% if project.deadline.mjd-a.mjd == 0%>
          <% project.sts = -1%>
          <% project.save%>
        <% end %>
        <td class="news_arrow">
          <button type="button" class="btn btn-primary open_full" data-toggle="modal" data-target="#modal_tasks_<%= project.id %>"><span class="glyphicon glyphicon-menu-right"  aria-hidden="true"></span></button>
          </button>
        </td>
      </tr>
    </table>
  </div>
  <div class="modal fade" id="modal_tasks_<%= project.id %>" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content news_modal">
        <div class="modal-header">
          <button type="button-large" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h2><%= project.title %></h2>
        </div>

        <h4><span style="font-weight:800; font-size:2rem;">До:</span> 12 августа 2017</h4>
        <h4><span style="font-weight:800; font-size:2rem;">Вознаграждение:</span> 100000000</h4>
        <%= image_tag project.user.avatar(:thumb),class:"task_img" %>
        <p class = "heading">Описание</p>
        <p><%=project.description%></p>
        <p class = "heading">Пример</p>
        <p>
          Необходимо создать онлайн-платформу для размещения задач от компаний.
           Верификация пользователей, не должна портить пользовательский опыт
           (т.е. будет легкой и удобной).
          Все пользователи должны иметь возможность видеть задачи, задавать вопросы,
          получать ответы.
        </p>
        <p class = "heading">Требования к человеку</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <div class="links">
          <div class="work_with_project_link">
            <% if user_signed_in?%>
            <div class="">
              <%= link_to 'Открыть страницу задачи', project %>
            </div>
              <% if current_user.check == false %>
                <% if project.sts == -1 %>
                  <h4>Проект уже завершен</h4>
                <% else %>
                  <% if current_user.email != project.mentor%>
                    <div class="follow_status">
                      <%= render "partials/follow_status", object: project %>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          </div>

          <div class="open_company_profile">
            <%= link_to "Открыть профайл компании", project.user%>
            <% if project.file.url(:original, false) != "/files/original/missing.png"%>
              <%= link_to "Download", project.file.url(:original, false) %>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

<div class="top">
  <ul>
    <li style="font-size:2rem; font-weight:bold;">Best users</li>

  </ul>
</div>


</body>


<script>
  $( window ).load(function() {
    if (window.location.href.indexOf('reload')==-1) {
        window.location.replace(window.location.href+'?reload');
    }
  });
</script>

app/views/projects/myprojects.html.erb
<% if user_signed_in? %>
  <% if current_user.check == true %>
    <h1>Ваши проекты</h1>
    <% @myprojects.each do |project| %>
    <% if project.user.email == current_user.email%>
    <div class="my_project_preview row col-lg-10 col-lg-offset-1 col-sm-10 col-xs-10 col-xs-offset-1 col-sm-offset-1" data-wow-duration="1.5s">
      <div>
        <div class="col-lg-2 col-md-2">
          <%= image_tag project.user.avatar(:thumb),class:"projects_preview_img" %>
        </div>
        <div class="my_project_preview_info col-lg-5">
          <p class = "my_project_title"><%= project.title %></p>
          <p class = "mentor">Mentor: <%= project.mentor %></p>
        </div>
        <div class="myright_text col-lg-4">
            До: <%= project.deadline %></br>
            <% a=Date.parse(Time.now.strftime("%Y/%m/%d"))%>
            Осталось дней: <%= (project.deadline.mjd-a.mjd) %></br>
            Цена: <%= project.price %> тг
        </div>

        <div class="message col-lg-1">
          <button type="button" class="btn btn-primary my_open_full" data-toggle="modal" data-target="#modal_tasks_<%= project.id %>"><span class="glyphicon glyphicon-menu-right"  aria-hidden="true"></span></button>
          </button>
        </div>
      </div>
      <div class="modal fade" id="modal_tasks_<%= project.id %>" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content news_modal">
            <div class="modal-header">
              <button type="button-large" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h2><%= project.title %></h2>
            </div>
            <div class="span">
              <h4 ><span style="font-weight:800; font-size:2rem;">До:</span> 12 августа 2017</h4>
              <h4 ><span style="font-weight:800; font-size:2rem;">Вознаграждение:</span>  <%= project.price %></h4>
            </div>

            <%= image_tag project.user.avatar(:thumb),class:"project_picture" %>
            <p class = "heading" style="padding-top:2%;">Описание</p>
            <p>
               <%=project.description%>
            </p>
            <p class = "heading">Пример</p>
            <p>
              Необходимо создать онлайн-платформу для размещения задач от компаний.
               Верификация пользователей, не должна портить пользовательский опыт
               (т.е. будет легкой и удобной).
              Все пользователи должны иметь возможность видеть задачи, задавать вопросы,
              получать ответы.
            </p>
            <p class = "heading">Требования к человеку</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <div class="links">
              <div class="">
                <%= link_to 'Открыть страницу задачи', project %>
              </div>
              <div class="link">
                <%= link_to 'Изменить задачу', edit_project_path(project),class:"link" %><br/>
              </div>
              <div class="link">
                <%= link_to 'Удалить задачу', project, method: :delete,
                            data: { confirm: 'Are you sure?' } %>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
      <% end %>
      <%end%>
  <% else %>
    <h1>Проекты которые вы делаете</h1>
    <% @myprojects.each do |project| %>
      <% if current_user.following?(project.id) %>
        <div class="my_project_preview row col-lg-10 col-lg-offset-1">
          <div>
            <div class="col-lg-2 col-md-2">
              <%= image_tag project.user.avatar(:thumb),class:"projects_preview_img" %>
            </div>
            <div class="my_project_preview_info col-lg-5">
              <p class = "my_project_title"><%= project.title %></p>
              <p class = "mentor">Mentor: <%= project.mentor %></p>
            </div>
            <div class="myright_text col-lg-4">
              <p>До: 12 августа 2017</br>
              Цена: <%= project.price %></p>
            </div>
            <div class="message col-lg-1">
              <button type="button" class="btn btn-primary my_open_full" data-toggle="modal" data-target="#modal_tasks_<%= project.id %>"><span class="glyphicon glyphicon-menu-right"  aria-hidden="true"></span></button>
              </button>
            </div>
          </div>
          <div class="modal fade" id="modal_tasks_<%= project.id %>" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
            <div class="modal-dialog modal-lg" role="document">
              <div class="modal-content news_modal">
                <div class="modal-header">
                  <button type="button-large" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h2><%= project.title %></h2>
                </div>

                <h4 class="span"><span style="font-weight:800; font-size:2rem;">До:</span> 12 августа 2017</h4>
                <h4 class="span"><span style="font-weight:800; font-size:2rem;">Вознаграждение:</span>  <%= project.price %></h4>
                <%= image_tag project.user.avatar(:thumb),class:"project_picture" %>
                <p class = "heading">Описание</p>
                <p>
                  <%=project.description%>
                </p>
                <p class = "heading">Пример</p>
                <p>
                  Необходимо создать онлайн-платформу для размещения задач от компаний.
                   Верификация пользователей, не должна портить пользовательский опыт
                   (т.е. будет легкой и удобной).
                  Все пользователи должны иметь возможность видеть задачи, задавать вопросы,
                  получать ответы.
                </p>
                <p class = "heading">Требования к человеку</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <div class="">
                  <%= link_to 'Открыть страницу задачи', project %>
                </div><br>
                <div class="links">
                  <%= render "partials/follow_status", object: project %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
    <h1>Проекты на которых вы менторствуете</h1>
    <% @myprojects.each do |project|%>
      <% if current_user.email == project.mentor%>
      <div class="my_project_preview row col-lg-10 col-lg-offset-1">
        <div>
          <div class="col-lg-2 col-md-2">
            <%= image_tag project.user.avatar(:thumb),class:"projects_preview_img" %>
          </div>
          <div class="my_project_preview_info col-lg-5">
            <p class = "my_project_title"><%= project.title %></p>
            <p class = "mentor">Mentor: <%= project.mentor %></p>
          </div>
          <div class="myright_text col-lg-4">
              До: <%= project.deadline %></br>
              <% a=Date.parse(Time.now.strftime("%Y/%m/%d"))%>
              Осталось дней: <%= (project.deadline.mjd-a.mjd) %></br>
              Цена: <%= project.price %> тг
          </div>

          <div class="message col-lg-1">
            <button type="button" class="btn btn-primary my_open_full" data-toggle="modal" data-target="#modal_tasks_<%= project.id %>"><span class="glyphicon glyphicon-menu-right"  aria-hidden="true"></span></button>
            </button>
          </div>
        </div>
        <div class="modal fade" id="modal_tasks_<%= project.id %>" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
          <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content news_modal">
              <div class="modal-header">
                <button type="button-large" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h2><%= project.title %></h2>
              </div>

              <h4 class="span"><span style="font-weight:800; font-size:2rem;">До:</span> 12 августа 2017</h4>
              <h4 class="span"><span style="font-weight:800; font-size:2rem;">Вознаграждение:</span>  <%= project.price %></h4>
              <%= image_tag project.user.avatar(:thumb),class:"project_picture" %>
              <p class = "heading">Описание</p>
              <p>
                <%=project.description%>
              </p>
              <p class = "heading">Пример</p>
              <p>
                Необходимо создать онлайн-платформу для размещения задач от компаний.
                 Верификация пользователей, не должна портить пользовательский опыт
                 (т.е. будет легкой и удобной).
                Все пользователи должны иметь возможность видеть задачи, задавать вопросы,
                получать ответы.
              </p>
              <p class = "heading">Требования к человеку</p>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <div class="links">
                <div class="">
                  <%= link_to 'Открыть страницу задачи', project %>
                </div>
                <div class="link">
                  <%= link_to 'Изменить задачу', edit_project_path(project),class:"link" %><br/>
                </div>
              </div>
            </div>
          </div>
        </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>


<script>
  $( window ).load(function() {
    if (window.location.href.indexOf('reload')==-1) {
        window.location.replace(window.location.href+'?reload');
    }
  });
</script>

app/views/projects/new.html.erb
<% if user_signed_in?%>
  <% if current_user.check == true %>
    <div class="new_project_header">
      <h1>Новый проект</h1>
    </div>

    <%= render 'form', project: @project %>
  <% else %>
    <h1>К сожалению, у вас нет полномочий на создание проекта</h1>
  <% end %>
<% end %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<table>
  <dl>

    <dt><%= @project.title %></dt>
    <dd><%= @project.description %></dd>
    <dt><%= @project.user.email %></dt>
    <dt><%= @project.price %></dt>
    <dt><%= @project.mentor %></dt>
    <dt><%= @project.sts %></dt>

    До: <%= @project.deadline %></br>
    <% a=Date.parse(Time.now.strftime("%Y/%m/%d"))%>
    <p class = "days_left">Осталось дней: <%= (@project.deadline.mjd-a.mjd) %></p>
    <% if @project.deadline.mjd-a.mjd == 0%>
      <% @project.sts = -1%>
      <% @project.save%>
    <% end %>

    <% if @project.sts == 1%>
      <h4>в процессе</h4>
    <% elsif @project.sts == 0%>
      <h4>в рассмотрении</h4>
    <% elsif @project.sts == -1%>
      <h4>закончен</h4>
    <% end %>
    <% count = 0 %>
    <% if @project.sts != -1 %>
      <% User.all.each do |user| %>
        <% if @project.followers?(user.id) %>
          <h4>developer: <%= link_to user.name, user %></h4>
          <% if user.name == ""%>
            <% @project.sts = 0%>
            <% @project.save%>
          <% else %>
            <% @project.sts = 1%>
            <% @project.save%>
            <% count+=1 %>
          <% end %>
        <% end %>
      <% end %>
      Проект делают: <%= count %>
    <% end %>
  </dl>
</table>
<% a = false %>
<% User.all.each do |user| %>
  <% if user.email == @project.mentor%>
    <% $mentor = user %>
  <% end %>
<% end %>

<% if @project.sts == -1%>
  <% if current_user.email == $mentor.email %>
    с кем вы закончили этот проект?<br>
    <form action = "<%= @project.id%>" >
      <input type="text" name="text1"> | <input type="submit"/> <br>
    </form>
    <% if @data != nil %>
      <% a = true %>
    <% end %>
    <% User.all.each do |user| %>
      <% if @project.followers?(user.id) %>
        <%= user.email %><br>
      <% end %>
    <% end %>
  <% end %>
<% end %>

  <% User.all.each do |user| %>
    <% if user.email == @data %>
      <% $developer = user %>
    <% end %>
  <% end %>

  <% if $developer != nil %>
    <% User.all.each do |user| %>
        <% if @project.sts == -1%>
          <% if current_user.email == $mentor.email %>
            <h1> Feedback about <%= $mentor.email %></h1>
            <% @reviewed = $developer %>
            <%= render @reviewed.ureviews %>
            <%= link_to "Add Reviews", new_reviewed_ureview_path(@reviewed)%>
          <% elsif current_user.email == $developer.email %>
            <h1> Feedback about <%= $developer.email %></h1>
            <% @reviewed = $mentor %>
            <%= render @reviewed.ureviews %>
            <%= link_to "Add Reviews", new_reviewed_ureview_path(@reviewed)%>
          <% end %>
        <% end %>
        <%break%>
      <% end %>
    <% end %>


<h1> Коментарии к проекту </h1>
<%= render @project.reviews %><br>
<%= link_to "Add Reviews", new_project_review_path(@project), class: "btn-custom" %>
<br>

<% if current_user.email == @project.user.email || current_user.email == @project.mentor%>
  <%= link_to 'Edit', edit_project_path(@project) %> |
<% end %>

<input type="button" onclick="history.back();" value="Назад"/>

<script>
 $('.review-rating').raty({
   readOnly: true,
   score: function() {
     return $(this).attr('data-source');
   },
   path: '/assets/'
 });
</script>
<!-- <script>
 $('.review-ratingtwo').raty({
   readOnly: true,
   score: function() {
     return $(this).attr('data-source');
   },
   path: '/assets/'
 });
</script>
<script>
 $('.review-ratingthree').raty({
   readOnly: true,
   score: function() {
     return $(this).attr('data-source');
   },
   path: '/assets/'
 });
</script>
<script>
 $('.review-ratingfour').raty({
   readOnly: true,
   score: function() {
     return $(this).attr('data-source');
   },
   path: '/assets/'
 });
</script>
<script>
 $('.review-ratingfive').raty({
   readOnly: true,
   score: function() {
     return $(this).attr('data-source');
   },
   path: '/assets/'
 });
</script> -->