config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :reviews
  end
  resources :users
  resources :revieweds do
    resources :ureviews
  end
  
  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
    member do
      post :restore
    end
    collection do
      delete :empty_trash
    end
    member do
     post :mark_as_read
   end
  end

  get '/hello/there', to: 'hello#there'
  root to: 'pages#home'
  get "/pages/:page" => "pages#show"
  get "pages/profile/myprojects" => "projects#myprojects"
  delete "/relationships", to: "relationships#destroy"
  resources :relationships, only: [:create]
  delete "/friendships", to: "friendships#destroy"
  resources :friendships, only: [:create]
  get "/my_friends", to: "users#my_friends"
  get "/users" => "users#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :relationships
  has_many :reviews
  def	followers?(user_id)
  		self.relationships.find_by_user_id(user_id)
	end

  validates :mentor, presence:true
  validates :price, numericality:true
  validate do |project|
    GoodnessValidator.new(project).validate
  end
  # Project.exists?(["mentor LIKE ?", "%#{params[:search]}"])

  has_attached_file :file
  validates_attachment :file, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document application/text) }

end

class GoodnessValidator
  def initialize(project)
    @project = project
  end

  def validate
    # if User.where(:name => @project_mentor).blank?
    if User.exists?(email: @project.mentor)
      nil
    else
      @project.errors[:base] << "Такого нету"
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/ureview.rb
class Ureview < ApplicationRecord
  belongs_to :user
  belongs_to :reviewed, class_name: 'User', foreign_key: 'reviewed_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  validates :name, presence:true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  acts_as_messageable

  has_many :projects
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100#", large: "600x600>"}, default_url: "http://www.pi-cube.com/wp-content/uploads/2015/04/team-placeholder.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_many :relationships
  has_many :reviews
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :ureviews

  def mailboxer_email(object)
    email
  end

  def	following?(project_id)
		self.relationships.find_by_project_id(project_id)
	end

  def followinguser?(friend_id)
    self.friendships.find_by_friend_id(friend_id)
  end
  def	followuser(friend_id)
		self.friendships.create(friend_id: friend_id)
	end
  def	unfollowuser(friend_id)
		self.friendships.find_by_friend_id(friend_id).destroy if followinguser?(friend_id)
	end
	def	follow(project_id)
		self.relationships.create(project_id: project_id)
	end
  def	unfollow(project_id)
		self.relationships.find_by_project_id(project_id).destroy if following?(project_id)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to projects_path
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_sign_in, only: [:show, :index, :my_friends]
  def index
    @users = User.where(["name LIKE ?","%#{params[:search]}"])
  end
  def show
    @user	=	User.find(params[:id])
  end
  def my_friends
    @friends = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, size = 30, title = user.name)
    image_tag gravatar_image_url(user.email, size: size), title: title, class: 'img-rounded'
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options(chosen_recipient = nil)
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}' data-img-src='#{gravatar_image_url(user.email, size: 50)}' #{'selected' if user == chosen_recipient}>#{user.name}</option>"
    end
    s.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/ureviews_helper.rb
module UreviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" id="nav">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header ">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://localhost:3000">.method</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
          </ul>
          <ul class="nav navbar-nav navbar-right">

            <li><a href="http://localhost:3000/pages/how_it_works" class ="main_page_link how">О проекте</a></li>
            <li><%= link_to "Задачи", projects_path,class:'main_page_link'%></li>

            <% if user_signed_in? %>
              <li><%= link_to "Все пользователи", users_path,class:'log_in_link'%></li>
              <% if current_user.notification != 0 %>
                <li> <a> <%= link_to current_user.notification, my_friends_path %> </a> </li>
              <%end%>
              <li class="dropdown">
                <a class="dropdown-toggle dropdown_link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email%>  <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a  href="http://localhost:3000/pages/profile">Мой профиль</a></li>
                  <li><a href="http://localhost:3000/pages/profile/myprojects">Мои задачи</a></li>
                  <li><%= link_to 'Your Conversations', conversations_path %></li>
                  <% if current_user.check == true %>
                  <li> <%= link_to 'Добавить задачу', new_project_path %></li>
                  <%end%>

                  <li><%= link_to('Выйти', destroy_user_session_path, method: :delete) %></li>

                </ul>
              </li>
            <%else%>
              <li><%= link_to('Войти', new_user_session_path,class:'log_in_link')  %></li>
              <li><%= link_to('Зарегистрироваться', new_user_registration_path,class:'sign_up_link')  %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <%if user_signed_in? %>
      <% ntf = 0 %>
      <% User.all.each do |friend| %>
        <% if !(current_user.followinguser?(friend.id) && friend.followinguser?(current_user.id))%>
          <% if friend.followinguser?(current_user.id) %>
            <% if current_user.email != friend.email %>
              <% ntf += 1%>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      <% current_user.notification = ntf %>
      <% current_user.save %>
    <% end %>
<!--//////////////////////////////////////////////////End of navbar///////////////////////////////////// -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Method</title>
    <link href="https://fonts.googleapis.com/css?family=Anonymous+Pro" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "application", media: "all","data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <%= render "layouts/header" %>
  <body class='<%= controller.controller_name %>'>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
      <script>new WOW().init();</script>
  </body>
</html>

app/views/partials/_follow_status.html.erb
<% if user_signed_in?%>
  <% if current_user.following?(object.id) %>
    <%= link_to "Прекратить работу над проектом", relationships_path(project_id: object.id), method: :delete ,class:"follow_link"%>
  <% else %>
    <%= link_to "Начать работу над проектом", relationships_path(project_id: object.id), method: :post,class:"follow_link" %>
  <% end %>
<% end %>

app/views/partials/_follow_sts.html.erb
<% if user_signed_in?%>
  <% if current_user.followinguser?(object.id) %>
    <%= link_to "Удалить менторство???", friendships_path(friend_id: object.id), method: :delete ,class:"profile_preview_links"%>
  <% else %>
    <%= link_to "Стать ментором", friendships_path(friend_id: object.id), method: :post ,class:"profile_preview_links" %>
  <% end %>
<% end %>

app/views/partials/_header.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %> |
     <a href="http://localhost:3000/pages/profile"><%= current_user.email %></a> |
      <% if current_user.check == false %>
        Пользователь
      <% else %>
        Компания
      <% end %>
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>
  </li>
<% end %>
<% if user_signed_in? %>
  <li>
  <%= link_to('Edit registration', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Register', new_user_registration_path)  %>
  </li>
<% end %>
<% if user_signed_in? %>
  <%= link_to "users", users_path%> |
  <%= link_to "convesations", conversations_path%> |
<% end %>
<%= link_to "Home", projects_path%>
<hr>